version: "3"
identidock:
services:
    build: 
      context: .
      ports:
        - 5000:5000
      environment:                                                                             
        ENV: DEV
      volumes:
        - ./app:/app