version: "3.8"
services:
  identidock:
    build: 
      context: .
    environment:
      ENV: DEV
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
    links:
      - dnmonster
  dnmonster:
    image: amouat/dnmonster:1.0
  redis:
    image: redis:3.0